### ISSUE TITLE
Issue installing Froxlor on OL8

### ISSUE THREAD

**Issue by maverick85** [Froxlor/Froxlor-Installer#1]
To install Froxlor on an EL8 system:

Since I'm using php7.4:
1. `dnf module install php:7.4`
2. `dnf install -y mariadb-server`
3. `systemctl enable --now mariadb`
4. `/usr/bin/mysql_secure_installation`
5. `php froxlor-install.phar`

Which generates the error that follows. This error is thrown after the installer connects to the database server correctly, creates a froxlor database, then fails.

```
[root@web1-fx ~]# php froxlor-install.phar
*
* Starting Froxlor shell-installer v0.2-alpha...
*
Checking PHP-version ...[ok]
Checking PHP PDO extension ...[ok]
Checking PHP session extension ...[ok]
Checking PHP ctype extension ...[ok]
Checking PHP simplexml extension ...[ok]
Checking PHP xml extension ...[ok]
Checking PHP filter extension ...[ok]
Checking PHP posix extension ...[ok]
Checking PHP mbstring extension ...[ok]
Checking PHP curl extension ...[ok]
Checking PHP json extension ...[ok]
Checking PHP bcmath extension ...[ok]
Checking PHP zip extension ...[ok]

Please enter the directory where Froxlor shall be installed to [/root]:/var/www/html
Would you like to download Froxlor now? [Y/n]:Y
--2020-12-23 11:41:45--  https://files.froxlor.org/releases/froxlor-latest.tar.gz
Resolving files.froxlor.org (files.froxlor.org)... 185.123.52.110, 2a10:ec2::185:123:52:110
Connecting to files.froxlor.org (files.froxlor.org)|185.123.52.110|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2509820 (2.4M) [application/x-gzip]
Saving to: _/tmp/froxlor-latest.tar.gz_

/tmp/froxlor-latest.tar.gz              100%[=============================================================================>]   2.39M  12.4MB/s    in 0.2s

2020-12-23 11:41:46 (12.4 MB/s) - _/tmp/froxlor-latest.tar.gz_ saved [2509820/2509820]

--2020-12-23 11:41:46--  https://files.froxlor.org/releases/froxlor-latest.tar.gz.sha1
Resolving files.froxlor.org (files.froxlor.org)... 185.123.52.110, 2a10:ec2::185:123:52:110
Connecting to files.froxlor.org (files.froxlor.org)|185.123.52.110|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 65 [application/x-gzip]
Saving to: _/tmp/froxlor-latest.tar.gz.sha1_

/tmp/froxlor-latest.tar.gz.sha1         100% [=============================================================================>]      65  --.-KB/s    in 0s

2020-12-23 11:41:46 (179 MB/s) - _/tmp/froxlor-latest.tar.gz.sha1_ saved [65/65]

Extracting froxlor to /var/www/html/froxlor
Enter the domain under wich Froxlor shall be reached, this normally
is the FQDN (Fully Qualified Domain Name) of your system.
If you don't know the FQDN of your system, execute 'hostname -f'.
This installscript will try to guess your FQDN automatically if
you leave this field blank, setting it to the output of 'hostname -f'
Enter your system's hostname [web1-fx.ger.domain.io]:
Enter the IP address of your system, under wich all
websites shall then be reached. This must be the same
IP address the domain you inserted above points to.
You *must* set this to your correct IP address.
Enter your system's ip-address [A.B.C.D]:
Enter the IP address of the MySQL server, if the MySQL
server is on the same machine, enter 'localhost' or
simply leave the field blank.
Enter mysql-host address [localhost]:
Enter the username of the MySQL root user.
The default is 'root'.
MySQL root user [root]:
Enter the password of the MySQL root user:...
Enter the password of the MySQL root user again:...
Testing MySQL root connection
Database connection successful
Enter the name of the database you want to use for Froxlor. The default is 'froxlor'
MySQL database name [froxlor]:froxlor_server1
Enter the username of the unprivileged MySQL user you want Froxlor to use.
The default is 'froxlor'.
CAUTION: any user with that name will be deleted!
MySQL unprivileged user [froxlor]:froxlor_user1
Enter the password of the MySQL unprivileged user:...
Enter the password of the MySQL unprivileged user again:...
Enter the username of the admin user you want in your Froxlor panel.
Default is 'admin'.
Froxlor admin user [admin]:
Enter the password of the Froxlor admin user:...
Enter the password of the Froxlor admin user again:...
Webserver user name [www-data]:apache
Preparing SQL database files ...
[ok]
Creating froxlor database ...
[ok]
Installing SQL database files ...
[ok]
Database error: PDOException: SQLSTATE[HY000] [1044] Access denied for user 'froxlor_user1'@'localhost' to database froxlor_server1' in phar:///root/froxlor-install.phar/installer.php:537
Stack trace:
#0 phar:///root/froxlor-install.phar/installer.php(537): PDO->__construct()
#1 phar:///root/froxlor-install.phar/installer.php(141): Action->_installBaseData()
#2 phar:///root/froxlor-install.phar/installer.php(99): Action->_run()
#3 phar:///root/froxlor-install.phar/classes/class.CmdLineHandler.php(157): Action->__construct()
#4 phar:///root/froxlor-install.phar/classes/class.CmdLineHandler.php(73): CmdLineHandler->_createAction()
#5 phar:///root/froxlor-install.phar/classes/class.CmdLineHandler.php(46): CmdLineHandler->__construct()
#6 phar:///root/froxlor-install.phar/installer.php(635): CmdLineHandler::processParameters()
#7 /root/froxlor-install.phar(9): include('phar:///root/fr...')
#8 {main}
```

**Comment by d00p** [comment]
most likely be fixed with 461833b as the passwords were wrongly lowercased on input
